# Generated by Django 2.0.9 on 2018-11-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181116_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_status',
            field=models.CharField(choices=[('0', 'Free'), ('1', 'Premium'), ('2', 'Enterprise')], default='0', max_length=1, verbose_name='Membership'),
        ),
    ]
